### ISSUE TITLE
Make `core` more generic so it can be used for other APIs

### ISSUE THREAD

**Issue by matthewgertner** [Raynes/tentacles#57]
I'm implementing an app that needs to use REST APIs for a number of services. I'm implementing a connector for Pivotal Tracker right now, and it looks to me like `tentacles.core` could be a good basis for this. I'd have to make it a bit more generic though (e.g. the API base URL has to be a parameter and not hardcoded, and there needs to be some way to add arbitrary headers).

Would you consider a pull request along these lines?

**Comment by joelittlejohn** [comment]
@matthewgertner I'm wondering if a general purpose API wrapper would be better implemented as a different library altogether. What do you think?

If you end up creating a library that can be used by this project then it may be possible to refactor this project to using it. If there are some new, essential steps needed use your new API wrapper library (like adding middleware), then tentacles can then do this, rather than requiring it from the person calling tentacles.

**Comment by Raynes** [comment]
I think this can be closed. Tentacles is not the perfect example.
